### ISSUE TITLE
PHP basics issues

### ISSUE THREAD

**Issue by novachok** [Natali2205/PHP-lessons-practice-#1]
https://github.com/Natali2205/PHP-lessons-practice-/blob/master/%D0%97%D0%B0%D0%B2%D0%B4%D0%B0%D0%BD%D0%BD%D1%8F1.php#L9
Молодець, попрацювала зі стрінгами ))) але я очікував простішого рішення: echo $var[1];
тим не менш, рішення зараховується

**Comment by Natali2205** [comment]
Дякую))) якщо треба перероблю)

**Comment by novachok** [comment]
Переробити треба для себе - що набути майстерність ;)
